// session.js — the spine of Reenter.
// Every module reads from and writes to this.
// Nothing meaningful happens outside of it.
// Designed to be saveable to disk later without restructuring.

export function createSession({ projectPath, mode }) {
  return {
    meta: {
      startedAt: new Date().toISOString(),
      mode,           // 'run' | 'reenter' | 'refactor'
      projectPath,
      projectName: projectPath.split('/').pop()
    },

    project: {
      structure: null,    // raw directory tree
      keyFiles: null,     // contents of key files
      summary: null       // plain english summary from AI
    },

    plan: {
      options: null,      // all derived options from analysis
      chosenOption: null, // the option the user picked
      steps: [],          // high level steps for chosen option
      currentStep: 0,     // index of current step
      completedSteps: []  // indices of confirmed completed steps
    },

    briefing: {
      presentation: null, // what the agent found, in plain english
      questions: [],      // the 2 targeted questions generated by the agent
      answers: {},        // keyed by question id
      synthesis: null     // the shared picture before step 1
    },

    history: [],          // full exchange log — every message, check, and response

    checks: []            // every command run, its output, and what AI concluded
  };
}

// Append an entry to the session history.
// type: 'ai' | 'user' | 'check' | 'system'
export function logHistory(session, type, content) {
  session.history.push({ type, content, at: new Date().toISOString() });
}

// Record a command that was run with the user's consent.
export function logCheck(session, { command, output, conclusion }) {
  session.checks.push({ command, output, conclusion, at: new Date().toISOString() });
}
